import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :foundry_web, FoundryWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "NqdqX0xNYqxz05nRLichAa+N4WJR4ijlRgLMkcLismBif5aPk1Du4mIk4KfR8kBy",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:foundry_web, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:foundry_web, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :foundry_web, FoundryWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/foundry_web/router\.ex$"E,
      ~r"lib/foundry_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :foundry_web, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Default LLM provider for Chat UI — OpenAI Codex CLI.
# Authenticate with `codex login`; override with CODEX_MODEL when needed.
# If CODEX_EXECUTABLE is an explicit path, Foundry validates that exact file and
# does not fall back to the bundled app binary when the path is missing or not executable.
config :foundry, :llm_provider, :codex

config :foundry, :claude_code,
  model: "haiku",
  timeout_ms: 120_000

config :foundry, :codex,
  model: System.get_env("CODEX_MODEL", "gpt-5.4-mini"),
  profile: System.get_env("CODEX_PROFILE"),
  sandbox: System.get_env("CODEX_SANDBOX", "workspace-write"),
  executable: System.get_env("CODEX_EXECUTABLE", "codex"),
  timeout_ms: 120_000

config :foundry, :lm_studio,
  base_url: System.get_env("LM_STUDIO_BASE_URL", "http://localhost:1234/v1"),
  model: System.get_env("LM_STUDIO_MODEL", "qwen3-coder-30b-a3b-instruct-mlx"),
  timeout_ms: 120_000,
  temperature: 0.2

# Configure igaming project root for System Map Viewer
config :foundry_web,
       :igaming_project_root,
       Path.expand("reference_projects/igaming", __DIR__ |> Path.dirname())
