import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :foundry_web, FoundryWeb.Endpoint,
  url: [host: "127.0.0.1", port: 4000],
  http: [ip: {127, 0, 0, 1}, port: 4000],
  cache_static_manifest: "priv/static/cache_manifest.json",
  check_origin: [
    "http://127.0.0.1:4000",
    "http://localhost:4000",
    "//127.0.0.1:4000",
    "//localhost:4000",
    "http://127.0.0.1",
    "http://localhost",
    "//127.0.0.1",
    "//localhost",
    "tauri://localhost",
    "tauri://localhost:4000"
  ],
  force_ssl: false

# Configure Swoosh API Client
config :swoosh, :api_client, Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
