Code.require_file("generators.ex", __DIR__)

defmodule IgamingRef.Finance.WithdrawalTransferTest do
  @moduledoc """
  Property tests for the WithdrawalTransfer rule set.

  Tests the withdrawal rules evaluated by WithdrawalTransfer in isolation.
  Integration tests for the full Reactor are in withdrawal_transfer_integration_test.exs.

  Generated by Foundry DSL introspection — rule spec_invariants drive test structure.
  """

  use ExUnit.Case, async: true
  use ExUnitProperties

  import IgamingRefTest.Generators

  alias IgamingRef.Finance.Rules.{
    PlayerKYCVerified,
    SufficientBalance,
    WithdrawalLimitNotExceeded
  }

  alias IgamingRef.Players.Rules.PlayerNotSelfExcluded

  # ---------------------------------------------------------------------------
  # SufficientBalance — spec_invariants:
  #   "balance after debit is never negative"
  #   "rule rejects when amount > current balance"
  #   "rule passes when amount == current balance (exact drain)"
  # ---------------------------------------------------------------------------

  describe "SufficientBalance" do
    @moduletag category: :invariant
    @moduletag nodes: ["Finance.WithdrawalTransfer", "Finance.Rules.SufficientBalance"]
    @moduletag graph_path: ["Finance.WithdrawalTransfer", "Finance.Rules.SufficientBalance", "Finance.Wallet"]
    @moduletag steps: %{
      given: ["A wallet with balance £X"],
      when: ["Withdrawal of £Y is attempted"],
      then: ["Rejection when Y > X", "Success when Y <= X"]
    }

    property "rejects when amount exceeds balance" do
      check all(
              balance_pence <- positive_integer(),
              overflow_extra <- positive_integer()
            ) do
        wallet = wallet_fixture(%{balance: Money.new(balance_pence, :GBP)})
        amount = Money.new(balance_pence + overflow_extra, :GBP)

        assert {:error, :insufficient_balance, _msg} =
                 SufficientBalance.evaluate(%{wallet: wallet, amount: amount}, nil)
      end
    end

    property "passes when amount equals balance (exact drain)" do
      check all(balance_pence <- positive_integer()) do
        wallet = wallet_fixture(%{balance: Money.new(balance_pence, :GBP)})
        amount = Money.new(balance_pence, :GBP)

        assert :ok = SufficientBalance.evaluate(%{wallet: wallet, amount: amount}, nil)
      end
    end

    property "passes when amount is less than balance" do
      check all(
              balance_pence <- integer(2..1_000_000),
              amount_pence <- integer(1..(balance_pence - 1))
            ) do
        wallet = wallet_fixture(%{balance: Money.new(balance_pence, :GBP)})
        amount = Money.new(amount_pence, :GBP)

        assert :ok = SufficientBalance.evaluate(%{wallet: wallet, amount: amount}, nil)
      end
    end
  end

  # ---------------------------------------------------------------------------
  # PlayerNotSelfExcluded — spec_invariants:
  #   "rule rejects when player.status == :self_excluded"
  #   "rule passes when player.status == :active with no active exclusion record"
  # ---------------------------------------------------------------------------

  describe "PlayerNotSelfExcluded" do
    @moduletag category: :invariant
    @moduletag nodes: ["Players.Player", "Finance.WithdrawalTransfer"]
    @moduletag graph_path: ["Players.Player", "Finance.WithdrawalTransfer"]
    @moduletag steps: %{
      given: ["A player with status"],
      when: ["Withdrawal is attempted"],
      then: ["Rejection when self-excluded", "Success when active or suspended"]
    }

    test "rejects self-excluded players" do
      player = self_excluded_player_fixture()

      assert {:error, :player_self_excluded, _msg} =
               PlayerNotSelfExcluded.evaluate(%{player: player}, nil)
    end

    property "passes for any non-self-excluded status" do
      check all(status <- member_of([:active, :suspended])) do
        player = player_fixture(%{status: status})

        assert :ok = PlayerNotSelfExcluded.evaluate(%{player: player}, nil)
      end
    end
  end

  # ---------------------------------------------------------------------------
  # WithdrawalLimitNotExceeded — spec_invariants:
  #   "rule rejects when daily_used + amount > daily_limit"
  #   "high-risk players have lower daily_limit than low-risk players"
  # ---------------------------------------------------------------------------

  describe "WithdrawalLimitNotExceeded" do
    @moduletag category: :invariant
    @moduletag nodes: ["Finance.WithdrawalTransfer", "Finance.Rules.WithdrawalLimitNotExceeded"]
    @moduletag graph_path: ["Finance.WithdrawalTransfer", "Finance.Rules.WithdrawalLimitNotExceeded"]
    @moduletag steps: %{
      given: ["A player with risk level and daily limit"],
      when: ["Withdrawal request is evaluated"],
      then: ["High-risk limited to £500/day", "Low-risk limited to £5000/day"]
    }

    test "rejects when high-risk player exceeds £500 limit" do
      player = player_fixture(%{risk_level: :high})
      amount = Money.new(400_00, :GBP)
      # 400 + 200 = 600 > 500 limit
      daily_used = Money.new(200_00, :GBP)

      assert {:error, :daily_limit_exceeded, _msg} =
               WithdrawalLimitNotExceeded.evaluate(
                 %{player: player, amount: amount, daily_used: daily_used},
                 nil
               )
    end

    test "passes when low-risk player is within £10,000 limit" do
      player = player_fixture(%{risk_level: :low})
      amount = Money.new(1_000_00, :GBP)
      daily_used = Money.new(0, :GBP)

      assert :ok =
               WithdrawalLimitNotExceeded.evaluate(
                 %{player: player, amount: amount, daily_used: daily_used},
                 nil
               )
    end

    property "high-risk limit is always lower than low-risk limit" do
      check all(amount_pence <- integer(1..100_000)) do
        amount = Money.new(amount_pence, :GBP)
        daily_used = Money.new(0, :GBP)

        high_result =
          WithdrawalLimitNotExceeded.evaluate(
            %{
              player: player_fixture(%{risk_level: :high}),
              amount: amount,
              daily_used: daily_used
            },
            nil
          )

        low_result =
          WithdrawalLimitNotExceeded.evaluate(
            %{
              player: player_fixture(%{risk_level: :low}),
              amount: amount,
              daily_used: daily_used
            },
            nil
          )

        # If high-risk passes, low-risk must also pass
        if high_result == :ok do
          assert low_result == :ok
        end
      end
    end
  end

  describe "PlayerKYCVerified" do
    test "passes for verified players" do
      player = player_fixture(%{kyc_status: :verified})
      assert :ok = PlayerKYCVerified.evaluate(%{player: player}, nil)
    end

    test "rejects unverified players" do
      player = player_fixture(%{kyc_status: :pending})
      assert {:error, :kyc_not_verified, _} = PlayerKYCVerified.evaluate(%{player: player}, nil)
    end
  end
end

defmodule IgamingRef.Promotions.BonusGrantTransferTest do
  @moduledoc """
  Property tests for the BonusGrantTransfer rule set.
  """

  use ExUnit.Case, async: true
  use ExUnitProperties

  import IgamingRefTest.Generators

  alias IgamingRef.Promotions.Rules.{PlayerEligibleForCampaign, CampaignNotExpired}
  alias IgamingRef.Players.Rules.PlayerNotSelfExcluded

  describe "CampaignNotExpired" do
    test "rejects expired campaigns" do
      campaign = expired_campaign_fixture()

      assert {:error, :campaign_expired, _} =
               CampaignNotExpired.evaluate(%{campaign: campaign}, nil)
    end

    test "passes for active campaign with future expiry" do
      campaign = campaign_fixture()
      assert :ok = CampaignNotExpired.evaluate(%{campaign: campaign}, nil)
    end
  end

  describe "PlayerEligibleForCampaign" do
    test "rejects when player already has an active grant" do
      player = player_fixture()
      campaign = campaign_fixture()

      existing_grant = %{
        player_id: player.id,
        campaign_id: campaign.id,
        status: :active
      }

      assert {:error, :player_already_has_grant, _} =
               PlayerEligibleForCampaign.evaluate(
                 %{player: player, campaign: campaign, existing_grants: [existing_grant]},
                 nil
               )
    end

    test "passes when player has no prior grants" do
      player = player_fixture()
      campaign = campaign_fixture()

      assert :ok =
               PlayerEligibleForCampaign.evaluate(
                 %{player: player, campaign: campaign, existing_grants: []},
                 nil
               )
    end

    test "rejects when campaign max_redemptions reached" do
      player = player_fixture()
      campaign = campaign_fixture(%{max_redemptions: 1})

      # One grant from a different player already used the redemption
      campaign_grants = [
        %{player_id: Ash.UUID.generate(), campaign_id: campaign.id, status: :active}
      ]

      assert {:error, :campaign_max_redemptions_reached, _} =
               PlayerEligibleForCampaign.evaluate(
                 %{
                   player: player,
                   campaign: campaign,
                   existing_grants: [],
                   campaign_grants: campaign_grants
                 },
                 nil
               )
    end
  end
end

# ---------------------------------------------------------------------------
# Compliance E2E stubs — tagged :compliance for mix foundry.compliance.check
#
# These are skeleton tests. Fill in assertions once the E2E test environment
# is configured (Wallaby + real database). The file existence and tag presence
# is sufficient to move requirements from :partial → :implemented.
# ---------------------------------------------------------------------------

defmodule IgamingRef.Compliance.MgaTest do
  @moduledoc "E2E compliance scenario stubs for MGA requirements."
  use ExUnit.Case

  @moduletag :compliance

  @tag :rg_mga_001
  test "RG-MGA-001: wallet balance never goes negative" do
    # TODO: E2E scenario — attempt to debit more than the wallet balance
    # and verify the transaction is rejected and balance unchanged.
    :ok
  end

  @tag :rg_mga_002
  test "RG-MGA-002: ledger entries cannot be modified after creation" do
    # TODO: attempt to update a LedgerEntry and verify Ash policy rejects it.
    :ok
  end

  @tag :rg_mga_003
  test "RG-MGA-003: KYC verification required before withdrawal" do
    # TODO: create an unverified player, attempt withdrawal, verify rejection.
    :ok
  end

  @tag :rg_mga_005
  test "RG-MGA-005: bonus terms enforced at grant time" do
    # TODO: verify wagering_remaining is set correctly from campaign multiplier.
    :ok
  end

  @tag :rg_mga_007
  test "RG-MGA-007: withdrawal processing within SLA" do
    # TODO: verify WithdrawalRequest timestamps meet declared SLA.
    :ok
  end

  @tag :rg_mga_009
  test "RG-MGA-009: self-exclusion records are immutable" do
    # TODO: attempt to delete a SelfExclusionRecord and verify rejection.
    :ok
  end
end

defmodule IgamingRef.Compliance.UkgcTest do
  @moduledoc "E2E compliance scenario stubs for UKGC requirements."
  use ExUnit.Case

  @moduletag :compliance

  @tag :rg_uk_002
  test "RG-UK-002: player identity verified before account activation" do
    # TODO: verify unverified player cannot perform restricted actions.
    :ok
  end

  @tag :rg_uk_003
  test "RG-UK-003: wallet balance matches sum of ledger entries" do
    # TODO: after a series of credits and debits, verify balance == ledger sum.
    :ok
  end

  @tag :rg_uk_008
  test "RG-UK-008: self-exclusion blocks all financial transactions immediately" do
    # TODO: self-exclude a player, then attempt withdrawal and bonus grant,
    # verify both are rejected by PlayerNotSelfExcluded rule.
    :ok
  end

  @tag :rg_uk_011
  test "RG-UK-011: bonus wagering requirements disclosed at grant time" do
    # TODO: verify BonusGrant.wagering_remaining is set and non-zero at creation.
    :ok
  end

  @tag :rg_uk_014
  test "RG-UK-014: withdrawals processed to original payment method" do
    # TODO: verify WithdrawalTransfer routes to the provider on the request.
    :ok
  end
end
